### ISSUE TITLE
ConversionPattern not enforced

### ISSUE THREAD

**Issue by Pragmateek** [jptoto/log4net.ElasticSearch#59]
Hello,

first thanks for your contribution which is really useful to us. :-)

All is running fine except that the **`ConversionPattern`** is not applied to messages.
In **ElasticSearch** we have the raw messages specified in `logger.Debug` without any decoration.

I've tried with a minimal configuration :

	<appender name="ElasticSearch" type="log4net.ElasticSearch.ElasticSearchAppender, log4net.ElasticSearch">
		<connectionString value="Server=localhost;Index=log;Port=9200;rolling=true"/>
		<layout type="log4net.Layout.PatternLayout">
			<conversionPattern value="*** %-4timestamp [%thread] %-5level %logger %ndc - %message%newline" />
		</layout>
	</appender>

I have debugged your code and found that in **`Repository.Add`** the **`logEvent`**s text is raw.
Not sure if this is normal at this step as I don't know when the **log4net** plumbing applies messages formatting.

Your feedback will be greatly appreciated.

Thanks in advance.

Best regards.

Mickael

**Comment by jptoto** [comment]
@Pragmateek Thanks for the report! I'll check into this ASAP and see if I've got it implemented correctly.

**Comment by Pragmateek** [comment]
@jptoto Thanks for the quick feedback!
I'm probably missing something and doing stupid things. :)

**Comment by jptoto** [comment]
@Pragmateek What field in the Elasticsearch document are you looking for the event information? Now that you've added this note, it's made me realize that the ConversionPattern may be completely irrelevant to logging in Elasticsearch since all the fields are logged in the ES document anyway. Since all the fields are there, there isn't really any work to be done by choosing a pattern as if it were in a text log file.

Which field in the Elasticsearch document are you looking for the converted text?

**Comment by Pragmateek** [comment]
@jptoto This is the **`message`** field.
I had the same reflexion before posting but I though it could be applied anyway as it may ease future searches: you only have to look to the **`message`** field without crafting queries that span multiple fields, and you could more easily compare with information extracted from files and console output.
But if this is by-design I'm completely OK with it and I can confirm this to my colleagues to adapt the way we use these logs. :)

**Comment by Pragmateek** [comment]
@jptoto Moreover one of my colleagues reminds me of another use-case where we can't do without the **`ConversionPattern`**: in order to identify which application is logging it is possible to add a tag like `[MyApplication]` to the **`ConversionPattern`** so that every message will be decorated accordingly.
Or if your appender supports addition of a dedicated field, say "appName", to the ElasticSearch index, this would be a cleaner alternative to messages decoration.
Thanks.

**Comment by jptoto** [comment]
@Pragmateek The application is available in the "domain" field of the ES document. That is the appdomain. I'm _pretty_ sure I've covered all the possible fields that are available from log4net so they are easily readable from the index. Really, that would remove the need to using a ConversionPattern because, unlike in text or DB log file where fields may be limited, in log4net.ElasticSearch, I simply log all the fields.

It's _possible_ to use the ConversionPattern to format the message field but I haven't had any requests for that as yet. This is an image showing a basic layout of how the doc would look in ES http://take.ms/fGQt2 and you can see in the domain field is the appdomain so you can tell which application is logging the message.

**Comment by Pragmateek** [comment]
@jptoto Thanks for these information.
So finally we've decided to let the message unformatted and play with the **`domain`** field if necessary.
Thanks again for your help and keep up the good job! :-)

**Comment by jptoto** [comment]
No problem! @Pragmateek I take the feedback seriously so please let me know if you have any other concerns or issues.

I'm going to update the documentation accordingly to mention that ConversionPattern isn't needed.
