### ISSUE TITLE
Can't read host entries

### ISSUE THREAD

**Issue by mcinnes01** [jptoto/log4net.ElasticSearch#64]
If you add a host entry for your elasticsearch server it fails to connect with elasticsearch when running in a console app. When running as a web application under IIS it can read your host entries and will connect to elasticsearch as expected.

The work around I found is to use the ip of your elasticsearch server.

**Comment by jptoto** [comment]
@mcinnes01 When you run the tests, is it a local test on your desktop? For modern Windows OSes, I'm finding that using the machine name resolves the ipv6 IP and it's failing. For example, when I use

`Server=jtoto01;Index=log;Port=9200;rolling=true`

Which is my local desktop, it fails. If I use "localhost" instead of "jtoto01" it seems to work ok and resolves to the correct ipv6 IP that Elasticsearch is listening on. 

You can force the Elasticsearch `network.host` setting inside of the `elasticsearch.yml` config file to force it to listen to a different interface.

``` yaml
# Set the bind address to a specific IP (IPv4 or IPv6):
#
# network.host: 192.168.0.1
```

Otherwise I don't _think_ there is a lot I can do here. I don't do anything special to resolve the server names. In fact, I don't do anything at all - I let Windows do the resolving.
