### ISSUE TITLE
LogicalThreadContext.Properties int and long are indexed and analyzed as string

### ISSUE THREAD

**Issue by rdehuyss** [jptoto/log4net.ElasticSearch#66]
We are adding the following info to the LogEvent using the LogicalThreadContext.Properties

- LogicalThreadContext.Properties["Url"] = requestUri;
- LogicalThreadContext.Properties["TimespanInMillis"] = elapsedMilliseconds; // => long
- LogicalThreadContext.Properties["StatusCode"] = statusCode; // => int

Yet, in Elastic this is all indexed as string. Is there a way to control it so that we can create dashboards in Kibana?

Thx for an otherwise excellent library!

**Comment by jptoto** [comment]
@rdehuyss I _think_ your best bet here is to use [Elasticsearch Templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html) in order to tell Elasticsearch how to choose a type for that field. If you install a template, each time a log index is created (as long as you use the same naming convention) it will force the type to be `int` or `long` appropriately for the fields you name.

Let me know if you need some further guidance on this. I should add a section to the docs about creating templates to make it a little more approachable for users.
