### ISSUE TITLE
WCF and log4net.elasticsearch

### ISSUE THREAD

**Issue by arunkumar987** [jptoto/log4net.ElasticSearch#67]
Is it possible to use log4net.elasticsearch in WCF Service application? I was not able to log messages when using it on WCF Service application. But when I moved logging to WCF Host application(self hosted console) I was able to log messages. Why is that?

**Comment by jptoto** [comment]
@arunkumar987 I'm not exactly sure why the logger wouldn't work with a WCF service except that maybe there is a threading issue with the WCF service. If it's an `async` class, it may be terminating before the logger can log, depending on your code. You may need to `await` the log call itself but I'm just guessing. There is otherwise nothing special going on that would cause log4net.Elasticsearch to fail to make the call.
