### ISSUE TITLE
Decompose HttpClient and serialization method

### ISSUE THREAD

**Issue by michal-duda** [jptoto/log4net.ElasticSearch#69]
Hi,

I have built new appender with custom logic based on your ElasticsearchAppender. I was easy to inherit and reuse most of the code including repository but I was not able to easily reuse HttpClient. The reason is that there is ToJson method used and it can't be easily replaced by some other implementation.

I think it would be better if HttpClient has dependency to some IJsonSerializer or something like that. If you agree with this I can do it and send you pull request.

Michal

**Comment by jptoto** [comment]
@michal-duda It wasn't originally developed to be inherited which is why the coupling is pretty tight on that one. I think it's great if that code helped you but I'm not sure I see the need to decouple it for the sake of _this_ particular code. If there is a reason to modify the json appender or enable multple deseralizers in the future I will look into doing this.

**Comment by michal-duda** [comment]
@jptoto I understand that it was meant to be used like that. Anyway I think would be nice to have way how to use let say JSON.net instead of default serializer.

**Comment by jptoto** [comment]
@michal-duda I'll take a look at doing this tonight. If it seems practical, I can add it in. I'm intentionally using the custom serializer to keep the library from having any dependencies other than log4net.
