### ISSUE TITLE
Performance issue when server is not available

### ISSUE THREAD

**Issue by vishalpatel-te** [jptoto/log4net.ElasticSearch#71]
When server specified in elastic appender connection string, run it to severe performance issues. Any suggestion on how to improve that.

**Comment by jptoto** [comment]
@vishalpatel-te unfortunately there isn't a good way to improve this process since the log4net call is blocking. It's a hazard of using an external source as the target for logging.

One other thing you could try is to use [Filebeat](https://www.elastic.co/products/beats/filebeat) instead of log4net.Elasticsearch. You can log to local files and configure Filebeat to send the logs to Elasticsearch. In this way, in case the Elasticsearch server isn't available you won't notice performance issues with your application.
