### ISSUE TITLE
LogStash

### ISSUE THREAD

**Issue by rajrao** [jptoto/log4net.ElasticSearch#78]
I am new to ELK. I was wondering why you didnt use logStash (write a logStash log4net appender) and instead wrote an appender directly into ElasticSearch?

**Comment by jptoto** [comment]
@rajrao the idea when I started this project was to write _all_ the log4net data directly to Elasticsearch and then a user could format it from there. The downside is that you don't get to use Logstash filters before the data arrives to Elasticsearch. However, in today's Elasticsearch landscape you can do more filtering directly at Elasticsearch similar to logstash using [ingest nodes](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/ingest.html). As well, if you don't want to log directly to Elasticsearch, you can use a log4net [file appender](https://logging.apache.org/log4net/release/config-examples.html) and then read/log those files to Elasticsearch by way of [filebeat](https://www.elastic.co/products/beats/filebeat)

A lot of those options weren't available when I started so I decided to log directly to Elasticsearch for my purposes. I should note that I wouldn't recommend using this appender for production because of [potential performance issues](https://github.com/jptoto/log4net.ElasticSearch/wiki/05-Performance-Considerations).
