### ISSUE TITLE
Numeric custom properties

### ISSUE THREAD

**Issue by martinto** [jptoto/log4net.ElasticSearch#89]
I am trying to log a custom property as a long integer. The code to add it looks like this:

````c#
LogicalThreadContext.Properties["log4net:ElapsedTime"] = timer.TimeTaken;
````

This has been added to the mappings:

````
           "properties": {
               "type": "object",
               "properties" : {
                   "log4net:UserName" : {"type" : "keyword"},
                   "log4net:ElapsedTime" : {"type" : "long"},
                   "log4net:Identity" : {"type" : "keyword"},
                   "IP" : {"type" : "keyword"},
                   "log4net:HostName" : {"type" : "keyword"},
                   "@timestamp" : {"type" : "keyword"}
               }
           },

````
The data is ending up in elasticsearch as a string. I am using elasticsearch 5.2.0 and this module at version 2.3.3 from NuGet.

I am fairly sure that this used to work. How can I fix this?

**Comment by jptoto** [comment]
@martinto When adding data to Elasticsearch in a new index with no schema, it does its best job to "guess" the data type of each field. In this case, unfortunately, it's guessing that your long integer is a string. This isn't controlled by log4net.Elasticsearch. The best thing to do is add a [template](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html) to your Elasticsearch instance so that each index that is created uses the template which would specify that field is created as a [long](https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html).

**Comment by martinto** [comment]
I have added a template as I showed above, but the field is still being treated as a string.

**Comment by martinto** [comment]
I have got it working now. I _think_ that I was loading the template too late.

**Comment by jamestoto** [comment]
Ahhh ok that'll do it. If you load the template with a naming convention that your indexes use it will be used for all your indexes.
